In [1]:
import numpy as np

## Data Setup

In [2]:
# m : number of training examples
m = 5
input_features = 2
output_layer = 1

# X = (input_features, training_examples) = training_data_shape
X = np.random.rand(input_features , m)

# Y = output labels (or classes)
Y = np.random.rand(1,1)

In [3]:
# Activation function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

## First layer calcualtions (Hidden layer)

**Here is model from deeplearnig.ai course**:
<img src="classification_kiank.png" style="width:600px;height:300px;">

**Explanation**:
   * w1, w2, w3, w4 are weights for 4 neurons in hidden layer.
   * b1, b2, b3, b4 are biases for hidden layers.

In [4]:
################ First Layer Calculations ################
np.random.seed(5)
w1 = np.random.rand(1,2)
w2 = np.random.rand(1,2)
w3 = np.random.rand(1,2)
w4 = np.random.rand(1,2)

b1 = np.random.rand(1,1)
b2 = np.random.rand(1,1)
b3 = np.random.rand(1,1)
b4 = np.random.rand(1,1)

z1 = np.dot(w1, X) + b1
z2 = np.dot(w2, X) + b2
z3 = np.dot(w3, X) + b3
z4 = np.dot(w4, X) + b4

# Final activations (calculated individually)
a1 = sigmoid(z1)
a2 = sigmoid(z2)
a3 = sigmoid(z3)
a4 = sigmoid(z4)

# Here stacked all activations in hidden layer just for comparing with full vectorized version later
A1 = np.stack((a1,a2,a3,a4), axis=0)
A1 = np.squeeze(A1).reshape((A1.shape[0], m))
print("Hidden layer outputs for all training examples :", A1.shape)

################ Second Layer Calculations ################
np.random.seed(4)
W2 = np.random.rand(4)
B2 = np.random.rand(1)
Z2 = np.dot(W2, A1) + B2
A2 = sigmoid(Z2)

print("Final layer outputs for all training examples (i.e. predictions) :" , A2.shape)
print(A2)

Hidden layer outputs for all training examples : (4, 5)
Final layer outputs for all training examples (i.e. predictions) : (5,)
[0.93407018 0.94632001 0.95783107 0.9573956  0.96062289]


## Using stacking as explained in lecture PPT
    * Here used only single matrix W1 and B1. (which is stacked version of w1, w2, w3, w4 for previous explanation)

In [5]:
################ First Layer Calculations ################
np.random.seed(5)
W1 = np.random.rand(4, 2)
B1 = np.random.rand(4, 1)
Z1 = np.dot(W1, X) + B1
A1 = sigmoid(Z1)

print("Hidden layer outputs for all training examples :", A1.shape)

################ Second Layer Calculations ################
np.random.seed(4)
W2 = np.random.rand(4)
B2 = np.random.rand(1)
Z2 = np.dot(W2, A1) + B2
A2 = sigmoid(Z2)
print("Final layer outputs for all training examples (i.e. predictions) :" , A2.shape)
print(A2)

Hidden layer outputs for all training examples : (4, 5)
Final layer outputs for all training examples (i.e. predictions) : (5,)
[0.93407018 0.94632001 0.95783107 0.9573956  0.96062289]


### And now with activation vector you can calculate class (Binary classification)

In [6]:
# Below code is read as : (if value in A2 is greater than 0.5, make it 1, else make it 0)
# No loop version
predictions = np.where(A2 > 0.5, 1, 0)
print(predictions)

[1 1 1 1 1]
